spring:
  application:
    name: spring-kafka

  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    streams:
      bootstrap-server: localhost:9092
      application-id: spring-kafka
  properties:
    default:
      deserialization:
        exception:
          #            handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
          handler: com.learnkafkastreams.exceptionhandler.StreamsDeserializationExceptionHandler
      production:
        exception:
          handler: com.learnkafkastreams.exceptionhandler.StreamsProductionExceptionHandler